# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 20:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import final_project.custom_storages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cookbook', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivateKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=36)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_following', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_follower', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, storage=final_project.custom_storages.MediaStorage(), upload_to='', verbose_name='img')),
                ('about_me', models.TextField(blank=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('favorites', models.ManyToManyField(blank=True, to='cookbook.Recipe')),
                ('followers', models.ManyToManyField(blank=True, to='accounts.Follower')),
                ('following', models.ManyToManyField(blank=True, to='accounts.Following')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
